# Setup
title:               A New Method
tagline:             'A New Method'
description:         ''
url:                 https://bernardr.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              bernard
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #
